# Generated by Django 3.0.8 on 2020-07-25 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=50, verbose_name='nom')),
                ('birthdate', models.DateTimeField(verbose_name='birthdate')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('email', models.EmailField(max_length=150, verbose_name='email')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'people',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contacts.Person')),
                ('field1', models.CharField(max_length=38, verbose_name='field1')),
                ('field2', models.CharField(max_length=38, verbose_name='field2')),
                ('field3', models.CharField(max_length=38, verbose_name='field3')),
                ('postal_code', models.CharField(max_length=5, verbose_name='postal code')),
                ('city', models.CharField(max_length=32, verbose_name='city')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
            },
        ),
    ]
