# Generated by Django 3.0.8 on 2020-07-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20200726_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='field1',
            field=models.CharField(max_length=38, verbose_name='field 1'),
        ),
        migrations.AlterField(
            model_name='address',
            name='field2',
            field=models.CharField(max_length=38, verbose_name='field 2'),
        ),
        migrations.AlterField(
            model_name='address',
            name='field3',
            field=models.CharField(max_length=38, verbose_name='field 3'),
        ),
    ]
