# Generated by Django 3.0.8 on 2020-08-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20200728_0031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'adresse', 'verbose_name_plural': 'adresses'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'personne', 'verbose_name_plural': 'personnes'},
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=32, verbose_name='ville'),
        ),
        migrations.AlterField(
            model_name='address',
            name='field1',
            field=models.CharField(max_length=38, verbose_name='champ 1'),
        ),
        migrations.AlterField(
            model_name='address',
            name='field2',
            field=models.CharField(blank=True, max_length=38, null=True, verbose_name='champ 2'),
        ),
        migrations.AlterField(
            model_name='address',
            name='field3',
            field=models.CharField(blank=True, max_length=38, null=True, verbose_name='champ 3'),
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=5, verbose_name='code postal'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthdate',
            field=models.DateField(verbose_name='date de naissance'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='téléphone'),
        ),
    ]
