# Generated by Django 3.1.1 on 2020-09-19 13:00

import contacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20200821_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthdate',
            field=models.DateField(validators=[contacts.models.validate_birthday], verbose_name='date de naissance'),
        ),
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('first_name', 'last_name', 'birthdate')},
        ),
    ]
