# Generated by Django 3.1.3 on 2021-01-01 21:58

import contacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20210101_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birthdate',
            field=models.DateField(blank=True, null=True, validators=[contacts.models.validate_birthday], verbose_name='date de naissance'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='téléphone'),
        ),
    ]
