# Generated by Django 3.1.1 on 2020-09-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='newsletter_subscription',
            field=models.BooleanField(default=False),
        ),
    ]
