# Generated by Django 3.0.8 on 2020-07-27 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0003_auto_20200727_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_number', models.CharField(max_length=50, unique=True, verbose_name='member number')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contacts.Person')),
            ],
            options={
                'verbose_name': 'member',
                'verbose_name_plural': 'members',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nom')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
            ],
            options={
                'verbose_name': 'period',
                'verbose_name_plural': 'periods',
            },
        ),
        migrations.CreateModel(
            name='MembershipPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='comment')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.Member')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.Period')),
            ],
        ),
    ]
