# Generated by Django 3.0.8 on 2020-07-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipperiod',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='comment'),
        ),
    ]
