# Generated by Django 3.0.8 on 2020-08-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20200728_0033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'adhérent', 'verbose_name_plural': 'adhérents'},
        ),
        migrations.AlterModelOptions(
            name='membershipperiod',
            options={'verbose_name': "période d'adhésion", 'verbose_name_plural': "périodes d'adhésion"},
        ),
        migrations.AlterModelOptions(
            name='period',
            options={'verbose_name': 'période', 'verbose_name_plural': 'périodes'},
        ),
        migrations.AlterField(
            model_name='member',
            name='member_number',
            field=models.CharField(max_length=50, unique=True, verbose_name="numéro d'adhérent"),
        ),
        migrations.AlterField(
            model_name='membershipperiod',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='commentaire'),
        ),
        migrations.AlterField(
            model_name='period',
            name='end_date',
            field=models.DateField(verbose_name='date de fin'),
        ),
        migrations.AlterField(
            model_name='period',
            name='start_date',
            field=models.DateField(verbose_name='date de début'),
        ),
    ]
