# Generated by Django 3.1.3 on 2020-12-02 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='protected/messages/attachments', verbose_name='image')),
                ('message', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='membership.message')),
            ],
            options={
                'verbose_name': 'pièce jointe',
                'verbose_name_plural': 'pièces jointes',
            },
        ),
    ]
