# Generated by Django 3.1.3 on 2021-01-01 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0006_auto_20201202_2213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
