# Generated by Django 3.1.1 on 2020-10-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_auto_20200929_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='type',
            field=models.IntegerField(choices=[(1, 'Classique'), (2, 'Fidélité')], verbose_name='type'),
        ),
    ]
