# Generated by Django 3.1.3 on 2020-12-01 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_auto_20201016_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='period',
        ),
        migrations.RemoveField(
            model_name='command',
            name='price',
        ),
        migrations.RemoveField(
            model_name='command',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='command',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='command',
            name='seat_number',
        ),
        migrations.RemoveField(
            model_name='command',
            name='tribune',
        ),
        migrations.RemoveField(
            model_name='command',
            name='type',
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='rang')),
                ('seat_number', models.IntegerField(verbose_name='numéro de siège')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='prix')),
                ('type', models.IntegerField(choices=[(1, 'Classique'), (2, 'Fidélité')], verbose_name='type')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscription.command')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.period')),
                ('rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='subscription.rate')),
                ('tribune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='subscription.tribune')),
            ],
        ),
    ]
