# Generated by Django 3.1.1 on 2020-09-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='newsletter_sended',
            field=models.BooleanField(default=False),
        ),
    ]
