# Generated by Django 3.0.8 on 2020-08-17 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top14', '0003_auto_20200813_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='withdrawn_team1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='withdrawn_team2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='last_ranking',
            field=models.IntegerField(default=0, verbose_name='ranking last season'),
        ),
    ]
