# Generated by Django 3.0.8 on 2020-08-19 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top14', '0004_auto_20200817_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='red_cards1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='red_cards2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='yellow_cards1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='yellow_cards2',
        ),
    ]
