# Generated by Django 3.0.8 on 2020-08-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top14', '0005_auto_20200819_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'match', 'verbose_name_plural': 'matchs'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'verbose_name': 'saison', 'verbose_name_plural': 'saisons'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'équipe', 'verbose_name_plural': 'équipes'},
        ),
        migrations.AlterField(
            model_name='match',
            name='conversions1',
            field=models.IntegerField(default=0, verbose_name='transformations domicile'),
        ),
        migrations.AlterField(
            model_name='match',
            name='conversions2',
            field=models.IntegerField(default=0, verbose_name='transformations extérieur'),
        ),
        migrations.AlterField(
            model_name='match',
            name='date_time',
            field=models.DateTimeField(verbose_name='date et heure'),
        ),
        migrations.AlterField(
            model_name='match',
            name='drops1',
            field=models.IntegerField(default=0, verbose_name='drops domicile'),
        ),
        migrations.AlterField(
            model_name='match',
            name='drops2',
            field=models.IntegerField(default=0, verbose_name='drops extérieur'),
        ),
        migrations.AlterField(
            model_name='match',
            name='penalties1',
            field=models.IntegerField(default=0, verbose_name='pénalités domicile'),
        ),
        migrations.AlterField(
            model_name='match',
            name='penalties2',
            field=models.IntegerField(default=0, verbose_name='pénalités extérieur'),
        ),
        migrations.AlterField(
            model_name='match',
            name='played',
            field=models.BooleanField(default=False, verbose_name='joué'),
        ),
        migrations.AlterField(
            model_name='match',
            name='round',
            field=models.IntegerField(choices=[(1, 'Journée 1'), (2, 'Journée 2'), (3, 'Journée 3'), (4, 'Journée 4'), (5, 'Journée 5'), (6, 'Journée 6'), (7, 'Journée 7'), (8, 'Journée 8'), (9, 'Journée 9'), (10, 'Journée 10'), (11, 'Journée 11'), (12, 'Journée 12'), (13, 'Journée 13'), (14, 'Journée 14'), (15, 'Journée 15'), (16, 'Journée 16'), (17, 'Journée 17'), (18, 'Journée 18'), (19, 'Journée 19'), (20, 'Journée 20'), (21, 'Journée 21'), (22, 'Journée 22'), (23, 'Journée 23'), (24, 'Journée 24'), (25, 'Journée 25'), (26, 'Journée 26')], default=1, verbose_name='journée'),
        ),
        migrations.AlterField(
            model_name='match',
            name='tries1',
            field=models.IntegerField(default=0, verbose_name='essais domicile'),
        ),
        migrations.AlterField(
            model_name='match',
            name='tries2',
            field=models.IntegerField(default=0, verbose_name='essais extérieur'),
        ),
        migrations.AlterField(
            model_name='match',
            name='withdrawn_team1',
            field=models.BooleanField(default=False, verbose_name='forfait domicile'),
        ),
        migrations.AlterField(
            model_name='match',
            name='withdrawn_team2',
            field=models.BooleanField(default=False, verbose_name='forfait extérieur'),
        ),
        migrations.AlterField(
            model_name='season',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='team',
            name='active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='team',
            name='last_ranking',
            field=models.IntegerField(default=0, verbose_name='classement de la saison précédente'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='team',
            name='penalty_points',
            field=models.IntegerField(default=0, verbose_name='points de pénalité'),
        ),
        migrations.AlterField(
            model_name='team',
            name='short_name',
            field=models.CharField(max_length=10, verbose_name='sigle'),
        ),
    ]
