# Generated by Django 3.1.3 on 2021-01-01 21:49

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50, verbose_name='sujet')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='corps')),
            ],
            options={
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(upload_to='protected/messages/attachments', verbose_name='image')),
                ('message', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='contacts_messages.message')),
            ],
            options={
                'verbose_name': 'pièce jointe',
                'verbose_name_plural': 'pièces jointes',
            },
        ),
    ]
