# Generated by Django 3.1.7 on 2021-05-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_messages', '0002_message_sended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sended',
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.IntegerField(choices=[(0, 'Non envoyé'), (1, "En cours d'envoi"), (2, 'Envoyé')], default=0, verbose_name='statut'),
        ),
    ]
