# Generated by Django 3.2.4 on 2021-08-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_messages', '0003_auto_20210522_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receivers',
            field=models.IntegerField(choices=[(0, 'Tout le monde'), (1, 'Adhérents'), (2, 'Non adhérents'), (3, 'Abonnés'), (4, 'Non abonnés')], default=0, verbose_name='destinataires'),
        ),
    ]
