# Generated by Django 3.2.4 on 2021-08-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_messages', '0004_message_receivers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receivers',
            field=models.IntegerField(choices=[(0, 'Tout le monde'), (1, 'Adhérents'), (2, 'Non adhérents')], default=0, verbose_name='destinataires'),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.IntegerField(choices=[(0, 'Non envoyé'), (1, "En cours d'envoi"), (2, 'Envoyé'), (3, 'Erreur')], default=0, verbose_name='statut'),
        ),
    ]
